#! /bin/bash

test_name=$1
loop_ct=$2

fail_ct=0
exit_status=0

i=0
while [ $i -lt $loop_ct ] 
 do
	echo
	echo "continuous run:" $test_name
	echo "loop count    :" $loop_ct
	echo "loop current  :" $i 
	echo "fail count    :" $fail_ct

	# launch the test
	bsmcl run $test_name

	# get exit status of test
	exit_status=$?

	# count failed tests
	if [ $exit_status -ne 0 ]; then
		fail_ct=$[fail_ct+1]
	fi


	# count loops
	i=$[i+1]
 done

exit
