#! /bin/bash

# This is the install script for System M-1. 
# If started with option "-make" the binaries will not be built.

version=002

set -e

#CS: check for ada compiler, gcc, make, ...
#CS: check for gtk3-devel
#CS: check for gtkada. must be installed from: https://github.com/AdaCore/gtkada

source_script_dir=scripts
source_img_dir=img

dest_conf_dir=$HOME/.M-1
dest_script_dir=$HOME/bin
echo "System M-1 installer version" $version

mkdir -p $dest_script_dir

procedure_copy_script()
	{
	name=$1
	#echo "-" $name
	cp $source_script_dir/$name $dest_script_dir
	}

procedure_operator_confirmation()
	{
	echo -n "proceed ? (y/n): "
	read key
	echo
	[ ! $key = "y" ] && 
		{
		echo "installation aborted by operator"
		exit 1
		}
	}

procedure_make()
	{
	target=$1
	echo "-" $target
	cd src/$target # change into source dir
	make clean # clean up
	make # compile
	make install # install
	make clean # clean up
	cd - # change back to origin dir
	}

procedure_gnatmake()
	{
	target=$1
	echo "-" $target
	cd src/$target # change into source dir
	./make_clean.sh
	./make.sh
	cd - # change back to origin dir
	}

[ ! -e $dest_conf_dir ] && 
	{
	echo "creating hidden configuration directory" $dest_conf_dir "..."
	cp -R conf/M-1 $HOME/.M-1
	}
#CS: ask user if configuration directory should be updated.

echo "copying image files in" $dest_conf_dir/img "..."
[ ! -e $dest_conf_dir/img ] && 
	{
	mkdir $dest_conf_dir/img
	}
cp -rf $source_img_dir/*.png $dest_conf_dir/img


echo "copying script files in" $dest_script_dir "..."
#echo "WARNING ! Already existing script files residing there will be overwritten !"
#procedure_operator_confirmation
	
procedure_copy_script impeagle
procedure_copy_script imporcad
procedure_copy_script open_report
procedure_copy_script run_and_log_sequence
procedure_copy_script mkproject
procedure_copy_script run_continuous
#procedure_copy_script set_breakpoint

lib_examples_uut_dir=M-1
if [ ! -e $HOME/$lib_examples_uut_dir ]
	then
		echo "creating lib, examples, doc and uut directory  ..."
		mkdir $HOME/$lib_examples_uut_dir
		echo "- uut directory  ..."	
		cp -R uut/ $HOME/$lib_examples_uut_dir/
		echo "- lib directory  ..."		
		cp -R lib/ $HOME/$lib_examples_uut_dir/
		#echo "- documentation directory  ..."		
		#cp -R doc/ $HOME/$lib_examples_uut_dir/
	else
		#echo "WARNING ! Updating device libraries, examples and documentation in "$HOME/$lib_examples_uut_dir "?"
		#procedure_operator_confirmation
		echo "updating:"
		echo "- lib directory ..."
		cp -R -u lib/ $HOME/$lib_examples_uut_dir/
		echo "- examples in uut directory ..."
		cp -R -u uut/ $HOME/$lib_examples_uut_dir/
		#echo "- documentation directory ..."
		#cp -R -u doc/ $HOME/$lib_examples_uut_dir/
fi

if [ ! "$1" = "-make" ] 
	then
		echo "compiling and installing ..."
		set +e
		procedure_make bsmcl
		procedure_make chkpsn
		procedure_make udbinfo
		procedure_make compseq
		procedure_make impbsdl
		procedure_make impkicad
		procedure_make imptestexpert
		procedure_make impzuken
		procedure_make impprotel
		procedure_make joinnetlist
		procedure_make mkinfra
		procedure_make mkintercon
		procedure_make mkmemcon
		procedure_make mknets
		procedure_make mkoptions
		procedure_make mktoggle
		procedure_make mkclock
		#procedure_make mkvmod
		#procedure_gnatmake bsmgui
fi

echo done
exit
