#! /bin/bash

# This script loads and runs all tests generated by script build_tests.sh

# On error, exit from this script.
set -e 

bsmcl load infra
bsmcl load intercon
bsmcl load ram_out_1
bsmcl load ram_out_2
bsmcl load ram_in
bsmcl load cluster_digital
bsmcl load cluster_analog
bsmcl load clk_slow
bsmcl load clk_master
bsmcl load vccio
bsmcl load intercon_slow

bsmcl run infra
bsmcl run intercon
bsmcl run ram_out_1
bsmcl run ram_out_2
bsmcl run ram_in
bsmcl run cluster_digital
bsmcl run cluster_analog
bsmcl run clk_slow
bsmcl run clk_master
bsmcl run vccio
bsmcl run intercon_slow

exit

