#! /bin/sh

# infrastructure and interconnect tests
bsmcl load infra
[ "$?" -ne 0 ] && exit 1
bsmcl load intercon1
[ "$?" -ne 0 ] && exit 1

# memory interconnect tests
bsmcl load sram_ic202
[ "$?" -ne 0 ] && exit 1
bsmcl load sram_ic203
[ "$?" -ne 0 ] && exit 1

# oscillator test
bsmcl load osc
[ "$?" -ne 0 ] && exit 1

# LED tests
bsmcl load LED_D401
[ "$?" -ne 0 ] && exit 1
bsmcl load LED_D402
[ "$?" -ne 0 ] && exit 1
bsmcl load LED_D403
[ "$?" -ne 0 ] && exit 1
bsmcl load LED_D404
[ "$?" -ne 0 ] && exit 1

exit

