#! /bin/sh

# infrastructure and interconnect tests
bsmcl run infra
[ "$?" -ne 0 ] && exit 1
bsmcl run intercon1
[ "$?" -ne 0 ] && exit 1

# memory interconnect tests
bsmcl run sram_ic202
[ "$?" -ne 0 ] && exit 1
bsmcl run sram_ic203
[ "$?" -ne 0 ] && exit 1

# oscillator test
bsmcl run osc
[ "$?" -ne 0 ] && exit 1

# LED tests
bsmcl run LED_D401
[ "$?" -ne 0 ] && exit 1
bsmcl run LED_D402
[ "$?" -ne 0 ] && exit 1
bsmcl run LED_D403
[ "$?" -ne 0 ] && exit 1
bsmcl run LED_D404
[ "$?" -ne 0 ] && exit 1

#bsmcl off
#[ "$?" -ne 0 ] && exit 1
exit

