#! /bin/sh
version=001
echo pack_m-1 version $version

bsc_firmware_version=v60

dir_dev=$HOME/cad/projects/m-1
echo directory of development : $dir_dev

dir_target=m-1
echo directory of target      : $dir_target
[ -e $dir_target ] && rm -rf $dir_target
mkdir $dir_target

#bin files
mkdir $dir_target/bin
cp $dir_dev/bin/bsmcl $dir_target/bin
#cp $dir_dev/bin/bsmgui $dir_target/bin
cp $dir_dev/bin/chkclasses $dir_target/bin
cp $dir_dev/bin/chkpsn $dir_target/bin
cp $dir_dev/bin/compseq $dir_target/bin
cp $dir_dev/bin/gm1 $dir_target/bin
cp $dir_dev/bin/impbsdl $dir_target/bin
cp $dir_dev/bin/joinnetlist $dir_target/bin
cp $dir_dev/bin/mkclock $dir_target/bin
cp $dir_dev/bin/mkinfra $dir_target/bin
cp $dir_dev/bin/mkintercon $dir_target/bin
cp $dir_dev/bin/mkmemcon $dir_target/bin
cp $dir_dev/bin/mknets $dir_target/bin
cp $dir_dev/bin/mkoptions $dir_target/bin
cp $dir_dev/bin/mkproject $dir_target/bin
cp $dir_dev/bin/mktoggle $dir_target/bin
cp $dir_dev/bin/open_report $dir_target/bin
cp $dir_dev/bin/run_and_log_sequence $dir_target/bin

#cad importer
mkdir $dir_target/bin/cad_import
cp $dir_dev/bin/cad_import/impeagle6x $dir_target/bin/cad_import
cp $dir_dev/bin/cad_import/impaltium $dir_target/bin/cad_import
cp $dir_dev/bin/cad_import/impzuken $dir_target/bin/cad_import
cp $dir_dev/bin/cad_import/imporcad $dir_target/bin/cad_import

#images
mkdir $dir_target/bin/img
cp $dir_dev/bin/img/*.png $dir_target/bin/img

#kermit scripts
mkdir $dir_target/bin/kermit
cp $dir_dev/bin/kermit/clrram $dir_target/bin/kermit
cp $dir_dev/bin/kermit/diag $dir_target/bin/kermit
cp $dir_dev/bin/kermit/dump_outram $dir_target/bin/kermit
cp $dir_dev/bin/kermit/loadtest $dir_target/bin/kermit
cp $dir_dev/bin/kermit/runtest $dir_target/bin/kermit
cp $dir_dev/bin/kermit/stoptest $dir_target/bin/kermit
cp $dir_dev/bin/kermit/version $dir_target/bin/kermit

#lib
mkdir $dir_target/bin/lib
cp $dir_dev/bin/lib/libgtkada-2.18.so.0 $dir_target/bin/lib
cp -d $dir_dev/bin/lib/libgtkada.so $dir_target/bin/lib

#snippets
mkdir $dir_target/bin/snippets
cp $dir_dev/bin/snippets/mkoptions.conf $dir_target/bin/snippets
cp $dir_dev/bin/snippets/scanpath.txt $dir_target/bin/snippets
cp $dir_dev/bin/snippets/test_init_general.txt $dir_target/bin/snippets

#train-z
mkdir $dir_target/bin/train-z
cp $dir_dev/bin/train-z/go $dir_target/bin/train-z
cp $dir_dev/bin/train-z/hex2bin $dir_target/bin/train-z
cp $dir_dev/bin/train-z/z80asm $dir_target/bin/train-z
cp $dir_dev/bin/train-z/bsc_$bsc_firmware_version.bin $dir_target/bin/train-z
cp $dir_dev/bin/train-z/bsc_$bsc_firmware_version.lis $dir_target/bin/train-z
cp $dir_dev/bin/train-z/bsc_$bsc_firmware_version.asm $dir_target/bin/train-z
cp $dir_dev/bin/train-z/bsc_$bsc_firmware_version.hex $dir_target/bin/train-z

#documentation
mkdir $dir_target/doc

#src
mkdir $dir_target/src
mkdir $dir_target/src/ada

module=bsmcl
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=compseq
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=gui
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/gm1.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=impbsdl
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=impzuken
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=joinnetlist
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=mkintercon
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=mknets
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=mkoptions
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module

module=mktoggle
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/$module.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/compile.sh $dir_target/src/ada/$module


module=lib
mkdir $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/csv.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/m1.adb $dir_target/src/ada/$module
cp $dir_dev/src/ada/$module/m1_internal.adb $dir_target/src/ada/$module


#example UUTs
mkdir $dir_target/uut
cp -R $dir_dev/uut/mmu $dir_target/uut


#configuration
mkdir $dir_target/conf
mkdir $dir_target/conf/.m-1
cp -R $dir_dev/conf/.m-1/m-1.conf $dir_target/conf/.m-1
cp -R $dir_dev/conf/.m-1/help_english.txt $dir_target/conf/.m-1


#compress
tar -jcf m-1.tar.bz2 $dir_target
#rm m-1.tar
rm -rf m-1
[ "$?" -ne 0 ] && exit 1

echo done
exit
